# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
